### ISSUE TITLE
Change the repo name

### ISSUE THREAD

**Issue by bmcfee** [omec/open-mic#6]
I don't like this name, for lots of reasons.

This project was intended as a community effort, and sticking one person's name on it sends exactly the wrong message.

**Comment by ejhumphrey** [comment]
agreed, better placeholder? open-mir-eval?

**Comment by ejhumphrey** [comment]
that was a mistake I'm prepared to own up to and correct, but I'm not feeling imaginative today and need help fixing

**Comment by bmcfee** [comment]
Didn't mean to put you on the spot -- but I did want to enter my objection into the record.

Anything "mir-eval" might be confusing, given the `mir_eval` package.

How about "A Web Service for Open Music Evaluation" (AWeSOME)?

(Or just SOME)

**Comment by ejhumphrey** [comment]
likewise, wanted to document my acknowledgement of the error. 

don't like the "S", like the "OME" ... maybe Open Music Evaluation Challenge / Campaign? everyone loves omec, and the icons would be easy

**Comment by ejhumphrey** [comment]
i've swapped it to `omec` to get it somewhere else faster. issue is not closed, pending consensus.

**Comment by bmcfee** [comment]
![image](https://cloud.githubusercontent.com/assets/1190540/17674917/9aa264dc-62f5-11e6-84f2-88d1a0e05d85.png)

**Comment by ejhumphrey** [comment]
alrighty, well we have a working codename until the rest of the team gets invited and we can vote proper

**Comment by lostanlen** [comment]
Here is my proposition (re-posted from my message at `community@ismir.net` with minor edits):

`COSMIR`

Community for Open, Sustainable Music Information Research


Some pros:
* quite easy to pronounce and spell. If you can spell ISMIR, you can spell COSMIR.
* the cosmos prefix makes it sound scalable. In Ancient Greek, cosmos refers to the whole universe as an orderly system, as opposed to chaos.
* has Community, Open, and Sustainable in it, three important principles from the McFee et al paper.
* rhymes with ISMIR
* allows for a distinctive logo
* does not already exist in the dictionary, so your search engine loves it. I did search it: Cosmir is a [(rare) Moldovan surname](http://nume.casata.md/index.php?l=ro&action=viewnume&id=17363), a [general-purpose shop](http://www.societe.com/societe/cosmir-503946402.html) in France, a [civil engineering company](http://cosmir.eu/) in Italy. In science, NASA had a Conical Scanning Millimeter-wave Imaging Radiometer ([CosMIR](https://airbornescience.nasa.gov/instrument/CoSMIR)) for calibration, which has been discontinued. What I retain is that searching cosmir in a web browser could soon lead to this project, unlike the other names already proposed.
* Most importantly, www.cosmir.net is available.

Some cons:
* does not have Evaluation in it — but isn’t Evaluation part of Research anyway ?
* does not contain « Distributed », « Incremental », or other principles from the McFee et al paper.

**Comment by urinieto** [comment]
While I like COSMIR and a few others proposed in the mailinglist, I would advocate for something that isn't necessarily an acronym. I like the naming of marsyas, theano, keras, and all of that stuff. Just my 2 cents.

**Comment by ejhumphrey** [comment]
I also like this approach, and was thinking along the lines of Archimedes
or the "how do you know she's a witch?" scene from Monty Python's "Holy
Grail"... but have nothing quite yet.

**Comment by urinieto** [comment]
I would vouch for anything Monty Python / The Hitchhiker's Guide to the Galaxy / Discworld related name (especially if it has something to do with *evaluation* --yeah, the witch assessment, or the 42 answer, or the invisible university peer review process).

**Comment by bmcfee** [comment]
> if it has something to do with evaluation

... you mean like the total perspective vortex?

**Comment by urinieto** [comment]
YES :metal:

**Comment by ejhumphrey** [comment]
for what it's worth, the knight who oversees the witch evaluation is named
Sir Bedevere (alt. Bedivere, or olde English, Bedwyr): https://en.wikipedia.
org/wiki/Monty_Python_and_the_Holy_Grail

also worth noting, the evaluation is conducted in front of an entire mob,
which seems fitting.

**Comment by ejhumphrey** [comment]
https://www.youtube.com/watch?v=zrzMhU_4m-g

**Comment by urinieto** [comment]
To name this project Sir Bedevere or simply Bedevere would make me extremely happy.

**Comment by ejhumphrey** [comment]
+1 bedevere

**Comment by julian-urbano** [comment]
+1 to the idea of bedevere as well, even if it's got to do with witches and ducks rather than horses lol
Thinking about making it easier to look up, I was thinking about making Sir Bedevere more like MIR Bedevere, or maybe Bedevereval, Bedereval or the like.

**Comment by julian-urbano** [comment]
Another 2 cents:
I think that making a reference to Galileo would be nice:
- Obvious reason is the more-or-less establishment of the scientific method through observation, which clearly has to do with evaluation.
- Defied authority since he was a child, which also applies to some degree when we wanna have everything as transparent as possible.
- He had music all around: his father, his son, and he himself were lutes, composed, etc.

I don't have any proposal yet, but wanted to see if the idea is well received.

Cheers

**Comment by julian-urbano** [comment]
Previous ideas in the acronym path were:
- IOME: innitiative for open mir evaluation
- CSOME: campaign for sustainable and open mir evaluation
- NOME: network for open mir evaluation (turns out to be a city in alaska)-> could add a letter at the beginning and make it recursive, like gnome
- XISEM: XISEM innitiative for sustainable evaluation in mir -> any other letter instead of X would make it too

**Comment by urinieto** [comment]
If we go the Bedevere route, I would prefer to keep the name as it is. Using the "MIR Bedevere" / "Bedevereval" variants would be a bit redundant, since I'm sure people interested in the project would easily find it when searching in the web for "MIR Bedevere" or "Evaluation Bedevere" (e.g., you just need to type in Google "MIR SALAMI" to find the SALAMI dataset, and that's no biggie plus keeps the name simpler).

**Comment by julian-urbano** [comment]
yep, you're right. Sounds like it'll be bedevere!

**Comment by ejhumphrey** [comment]
haha hey now, we must let the democratic process run it's due course.

**Comment by ejhumphrey** [comment]
in light of recent points raised on the community mailing list, we should revisit this discussion. We've got a few extra names to consider now, and perhaps we can prune the ones that got <2 votes the last time around. I'll throw together another google form today and we'll have an abbreviated voting cycle. keep your eyes peeled!

**Comment by ejhumphrey** [comment]
hi team, after pruning the names that got >85% no thanks, we're really only left with a few options. Therefore, this form is a little bit different. Please vote for org name, project name, or both, and we'll see what the averages look like.

https://goo.gl/forms/QQ27Wc2hmMFMqN0g1

apologies for also sending this as an email in a second.

**Comment by superbock** [comment]
Folks, please wait a second. Do you seriously consider/propose to rename it again, just because some people -- not even involved with the project at all? (I'm not sure about this, since there's no official list of people involved available) -- dislike the name for whatever reason? IMHO this is ridiculous... And yes, I read their arguments on the music-ir list.

**Comment by ejhumphrey** [comment]
Yes, we are going to rename the project. I'd like this initiative to be successful _and_ well received by the community, hopefully at ISMIR2017. Currently, the name on which we achieved consensus is directly undermining the latter goal.

**Comment by julian-urbano** [comment]
so much desire to be politically incorrect right now...
